name: learning expressions

on: 
  workflow_dispatch:
  push:
    branches:
      - main
      - '!feature/**'
  pull_request:
    branches:
      - main

jobs:
  runs-on-main:
    if: github.ref == 'refs/heads/main'
    concurrency:
      group: test-group
      cancel-in-progress: true
    runs-on: ubuntu-latest
    steps:
    - name: return github event and branch name
      run: echo ${{ github.event }} and branch is ${{github.ref}}