name: learning expressions

on: 
  workflow_dispatch:
  push:
    branches:
      - main
      - '!feature/**'

jobs:
  runs-on-main:
    if: github.ref == 'refs/heads/main'
    runs-on: ubuntu-latest
    steps:
    - name: return github event and branch name
      run: echo ${{ github.event }} and branch is ${{github.ref}}