name: test matrix startegy

on:
  workflow_dispatch:
    
jobs:
  job1:
    runs-on: ubuntu-latest
    steps:
    - name: docker info
      run: docker info

    - name: docker run
      run: docker run hello-world

