name: test matrix startegy

on:
  workflow_dispatch:
    
jobs:
  job1:
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest]
        image: [hello-world, alpine]

    runs-on: ubuntu-latest
    steps:
    - name: docker info from ${{ matrix.os }}
      run: docker info

    - name: docker run from ${{ matrix.os }} for image ${{ matrix.image }}
      run: docker run hello-world

